### ISSUE TITLE
Add more `integration-test` tests

### ISSUE THREAD

**Issue by jakoschiko** [duesee/imap-next#118]
We need to write tests using the `integration-test` framework introduced in #114.

- [x] `crtl_relaxed` is true, `\n` can be parsed (#133)
- [x] `ctrl_relaxed` is false, `\n` causes malformed (#133)
- [x] literal was accepted (#119)
- [x] literal was rejected (#119)
- [x] literal with non-sync (#230)
- [x] idle accepted (#218)
- [x] idle rejected (#218)
- [x] authenticate accepted (#227)
- [x] authenticate rejected immediately (#227)
- [x] authenticate rejected later (#227)
- [ ] ~~does not panic if functions are called randomly~~ delegated to #232
- [x] server and client send in parallel, see #134 (#231)

For each case we need to consider whether we want to test client, server, or both.

**Comment by jakoschiko** [comment]
[arbtest](https://crates.io/crates/arbtest) looks like a good candidate for tests with random data.

**Comment by duesee** [comment]
Uuuuh, looks nice.

**Comment by jakoschiko** [comment]
Hmm, I'm not happy with arbtest. I wasn't able to generate `Vec<Vec<u8>>` with significant lengths. [See this example](https://www.rustexplorer.com/b#LyoKW2RlcGVuZGVuY2llc10KYXJidGVzdCA9ICIwLjMuMSIKKi8KCnVzZSBhcmJ0ZXN0OjphcmJ0ZXN0OwoKZm4gbWFpbigpIHsKICAgIGFyYnRlc3QofHV8IHsKICAgICAgICBsZXQgeDogVmVjPFZlYzx1OD4+ID0gdS5hcmJpdHJhcnkoKT87CiAgICAgICAgcHJpbnRsbiEoInt4Oj99Iik7CiAgICAgICAgT2soKCkpCiAgICB9KQogICAgLmJ1ZGdldF9tcygxMDAwKQogICAgLnNpemVfbWluKDEwMDAwMCkKICAgIC5zaXplX21heCgxMDAwMDAwMDApOwp9Cg==).

```rust
use arbtest::arbtest;

fn main() {
    arbtest(|u| {
        let x: Vec<Vec<u8>> = u.arbitrary()?;
        println!("{x:?}");
        Ok(())
    })
    .budget_ms(1000)
    .size_min(100000)
    .size_max(100000000);
}
```

produces

```
[]
[[]]
[]
[[156], [215], [19, 242, 169], [52, 80]]
[]
[[], [187], [188, 201], []]
[[254]]
[[67, 103, 177, 41], [248, 238, 176]]
[]
[[46], [64, 132, 79, 59, 79], [], [], [235], [], []]
[]
[[112]]
[]
[]
[]
[]
[[], [87, 206], [233], [], []]
[]
[]
[]
[[50]]
[]
[[], []]
[[234], [46, 49]]
[]
[[11]]
[[191], [], [76, 242, 1]]
[[]]
[]
[[37]]
[]
[]
[]
[]
[]
[]
[]
[]
[[], [], [], []]
[]
[]
[[]]
[[38, 136, 103], [10]]
[[], [221]]
[]
```

Quite disappointing for 1s runtime and 100000 min bytes. Not sure if I'm doing something wrong.

**Comment by duesee** [comment]
Hm... What hapens if you put an `assert!(x.len() < 500)` after the `println`?

**Comment by jakoschiko** [comment]
You can see all (!) generated values in my comment.

**Comment by jakoschiko** [comment]
My conclusion: arbtest is inherently flawed and we shouldn't use arbitrary for property testing.

arbitrary expects that it is used with some kind of feedback loop for its `Unstructured`. All collections are generated using this `Iterator` for generating elements:

```rust
impl<'a, ElementType: Arbitrary<'a>> Iterator for ArbitraryTakeRestIter<'a, ElementType> {
    type Item = Result<ElementType>;
    fn next(&mut self) -> Option<Result<ElementType>> {
        let keep_going = self.u.arbitrary().unwrap_or(false);
        if keep_going {
            Some(Arbitrary::arbitrary(&mut self.u))
        } else {
            None
        }
    }
}
```

If `Unstructured` is just random bytes, then the collection is very short with a high probabilty. And arbtest is using random bytes. I don't see how arbtest could fix that without mutating into a full-fledged fuzzing tool.
