### ISSUE TITLE
chore: A new home for `proxy`

### ISSUE THREAD

**Issue by duesee** [duesee/imap-next#132]
The proxy is great and deserves its own repository -- we should move it.

# TODO

* [x] Create `duesee/imap-proxy` and add @jakoschiko
* [x] Rename `proxy` to `imap-proxy`
* [x] Use `README.md` similar to `imap-{types,codec,next}` (https://github.com/duesee/imap-proxy/issues/9)
* [x] Update references to `proxy` in related repositories
* [x] Update references to `proxy` on related sites
* [x] Publish `imap-next` and use in `imap-proxy` (alternatively use git ref for now)
* [x] Move issues related to `proxy` to `duesee/imap-proxy`

**Comment by jakoschiko** [comment]
Can we fix the (trivial) TODOs before we move it?

**Comment by duesee** [comment]
Sure! I just filed this issue as a reminder. Won't do anything dumb w/o talking with you first ;-)

**Comment by duesee** [comment]
Create duesee/imap-proxy and give @jakoschiko super contributor rights for life.
