### ISSUE TITLE
Release imap-flow 0.1.0

### ISSUE THREAD

**Issue by duesee** [duesee/imap-next#195]
# Before Release

* [x] Check for warnings
* [x] Does everything still compile?
* [x] Does the proxy still work?
  * #204 -> not relevant for `imap-flow` 
* [x] #199
* [x] #105 (blocked by #199)
* [x] Improve Cargo.toml metadata
  * [x] `warning: manifest has no description, documentation, homepage or repository` (#205)
* [x] Check what is uploaded to crates.io
  * [x] Exclude `.github` from `cargo package --list`
  * [x] Exclude `proxy`
* [x] Polish `README.md`, add example, etc. (#205)
* [x] Close ...
  * [x] #200 -> Let's not block on that. 
  * [x] #170 (#208)
  * [x] #168
  * [x] #147 -> This is better handled by https://github.com/duesee/imap-codec/issues/368
  * [x] Wait for `imap-codec` and `imap-types` release?

# After Release

* #8

**Comment by duesee** [comment]
FYI: @soywod. Current plan is to release imap-flow soonish (hopefully end of this week.)

**Comment by soywod** [comment]
Does it includes other workspaces like `task`, `tag-generator` etc? Regarding tasks, any news if they should move to a dedicated repo (with the client) or not?

**Comment by duesee** [comment]
`imap-tasks` not. Hm... `tag-generator` I don't know. I like how small and helpful it is. Any suggesstion? `proxy` should eventually get its own repository as it's too good to be hidden here :-)

**Comment by soywod** [comment]
> You inlined `imap-tasks` already in `imap-client`, right? Thus, I propose to remove it here quickly :-)

I initiated sth so I could close the PR and replace crate inside `email-lib`, nothing definitive. It depends on your decision with @jakoschiko. Let me know :slightly_smiling_face: 

> I feel like `tag-generator` should be inlined into `imap-types`. Not ideal but the best option I see. Other suggesstions?

Does not fit either `imap-types` nor `imap-codec`, and it looks "too small" to fit in a dedicated repository. Mmh. What about a `imap-utils`? The proxy could even fit there?

**Comment by soywod** [comment]
Looks like there is not so much remaining except for:

- https://github.com/duesee/imap-flow/issues/199#issuecomment-2140931484
- `imap-{types,codec}` release

Do you confirm?

**Comment by duesee** [comment]
Yes 💪🏻

**Comment by duesee** [comment]
https://crates.io/crates/imap-next 🎉
